In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [4]:
d = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [5]:
d[1][2]

5

In [6]:
d[1,2]

5

In [7]:
d[1:,3:]

array([[6, 7],
       [9, 9]])

In [8]:
d = np.array([2,3,4,5,6])
d

array([2, 3, 4, 5, 6])

In [9]:
d.shape

(5,)

In [10]:
e = np.array([[1,2,3,4],[3,4,5,6]])
e

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [11]:
e.shape

(2, 4)

In [12]:
d.dtype

dtype('int32')

In [13]:
data = np.arange(1,5)

In [14]:
data.dtype

dtype('int32')

In [15]:
data.astype('float')

array([1., 2., 3., 4.])

In [16]:
data.astype('int')

array([1, 2, 3, 4])

In [17]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a.transpose()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
b = np.transpose(a)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,23,14],[36,47,58]])
arr1
arr2

array([[2, 3, 4],
       [6, 7, 8]])

array([[12, 23, 14],
       [36, 47, 58]])

In [24]:
arr1 + arr2

array([[14, 26, 18],
       [42, 54, 66]])

In [25]:
arr1 * arr2

array([[ 24,  69,  56],
       [216, 329, 464]])

In [26]:
arr1 / arr2

array([[0.16666667, 0.13043478, 0.28571429],
       [0.16666667, 0.14893617, 0.13793103]])

In [27]:
arr3 = np.array([100,200,300])

In [28]:
arr1.shape

(2, 3)

In [29]:
arr3.shape

(3,)

In [30]:
arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])

In [31]:
arr4 = np.arange(11)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr4.shape

(11,)

In [33]:
# 행과 열의 크기가 모두 다른 배열은 더할 수 없다.
arr1 + arr4

ValueError: operands could not be broadcast together with shapes (2,3) (11,) 

In [34]:
arr5 = np.array([[9],[3]])

In [35]:
arr5.shape

(2, 1)

In [36]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [37]:
arr5+arr1

array([[11, 12, 13],
       [ 9, 10, 11]])

In [38]:
d = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9,]])

In [39]:
d_list = [[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]]

In [40]:
d
d_list

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

[[1, 2, 3, 4, 5], [2, 4, 5, 6, 7], [5, 7, 8, 9, 9]]

In [41]:
type(d_list)

list

In [42]:
# 리스트를 슬라이싱해 0을 저장하라고 명령하면 오류발생.
d_list[:2] = 0

TypeError: can only assign an iterable

In [43]:
d[:2] =0
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [5, 7, 8, 9, 9]])

In [44]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr4[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr4[-3:]

array([7, 8, 9])

In [47]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [48]:
arr1[1,2]

8

In [49]:
arr1[:,2]

array([4, 8])

In [50]:
import pandas as pd

In [58]:
quest = pd.read_csv('data/quest.csv', header=None)

In [59]:
quest = np.array(quest).astype(float)
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 6., 2., 5.],
       [3., 6., 4., 2., 5.],
       [3., 5., 4., 1., 6.],
       [3., 5., 5., 1., 3.]])

In [60]:
quest > 5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [61]:
quest[quest > 5]

array([6., 6., 6.])

In [62]:
quest[quest > 5] = 5
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])